### ISSUE TITLE
谢谢你们的开源作品

### ISSUE THREAD

**Issue by deepkolos** [xshwz/amsproxy#1]
我是惠州学院大二的一个学生,惠大微报的技术部的,看到你们这个这么好的移动教务系统,我们就拿来做二次开发了,在关于那里会谢谢你们的贡献的

对于还没接触php框架的我,看到你们的作品模块化的程度真的好高啊!!搞到我也打算学习Yii框架了,哈哈~

对了, 遇到一个问题, 就是我想记录上次登陆的学号, 在cookies里面, 但是不知道为什么登陆进去, cookies写入了, 但是一旦页面切换了, 这个cookies就被清除掉了, 我cookies设置的过期时间为一个星期的, 感觉好奇怪

**Comment by qiuxiang** [comment]
很高兴看到我们开发的作品现在还能给别人带来帮助，虽然我们已经不再维护了。

现在再看 yii 框架，当时确实是非常好的选择，可控性很好，但现在如果重新做一个这样的项目，我可能会考虑用其他语言来写比如
nodejs、python，就算是用 php 现在也有优于 yii 的备选，比如 laravel，或其他基于路由的微型框架比如 lumen。

关于 cookies 的问题，既然已经提了 issue，那我就在 github 上回复吧。

DeepKolos <notifications@github.com>于2017年1月19日周四 下午9:35写道：

**Comment by qiuxiang** [comment]
可能是你没有设置 cookies 的 path 为根目录

**Comment by deepkolos** [comment]
[faceplam],原来把过期时间设置错了,没有加上time(),[faceplam]
